### ISSUE TITLE
FR: Support for Sony WH-1000XM5/XM4/XM3

### ISSUE THREAD

**Issue by ondern** [d4rken-org/capod#148] opened 2023-07-04 16:28 UTC
FR: Support for Sony WH-1000XM5/XM4/XM3

**Comment by d4rken** [comment] 2023-07-04 16:35
Duplicate of #15, I think if communication is figured out for one for the XM headsets, it should be easy to support all.

**Closed by d4rken** 2023-07-04 16:35 UTC
Labels: enhancement, new device
